import { Schedule, TimeSlot } from '@/prismaClient';
import { ScheduleResponseDto } from '../dto';
import { mapTimeSlotToResponseDto } from './timeSlot.mapper';

export const mapScheduleToResponseDto = (
  schedule: Schedule & { timeSlots: TimeSlot[] }
): ScheduleResponseDto => {
  return {
    placeId: schedule.placeId,
    id: schedule.id,
    name: schedule.name,
    repeatMode: schedule.repeatMode,
    startDate: schedule.startDate.toISOString(),
    stopDate: schedule.stopDate.toISOString(),
    repeatStep: schedule.repeatStep,
    m1: schedule.m1,
    m2: schedule.m2,
    m3: schedule.m3,
    m4: schedule.m4,
    m5: schedule.m5,
    m6: schedule.m6,
    m7: schedule.m7,
    m8: schedule.m8,
    m9: schedule.m9,
    m10: schedule.m10,
    m11: schedule.m11,
    m12: schedule.m12,
    w1: schedule.w1,
    w2: schedule.w2,
    w3: schedule.w3,
    w4: schedule.w4,
    wLast: schedule.wLast,
    wd1: schedule.wd1,
    wd2: schedule.wd2,
    wd3: schedule.wd3,
    wd4: schedule.wd4,
    wd5: schedule.wd5,
    wd6: schedule.wd6,
    wd7: schedule.wd7,
    d1: schedule.d1,
    d2: schedule.d2,
    d3: schedule.d3,
    d4: schedule.d4,
    d5: schedule.d5,
    d6: schedule.d6,
    d7: schedule.d7,
    d8: schedule.d8,
    d9: schedule.d9,
    d10: schedule.d10,
    d11: schedule.d11,
    d12: schedule.d12,
    d13: schedule.d13,
    d14: schedule.d14,
    d15: schedule.d15,
    d16: schedule.d16,
    d17: schedule.d17,
    d18: schedule.d18,
    d19: schedule.d19,
    d20: schedule.d20,
    d21: schedule.d21,
    d22: schedule.d22,
    d23: schedule.d23,
    d24: schedule.d24,
    d25: schedule.d25,
    d26: schedule.d26,
    d27: schedule.d27,
    d28: schedule.d28,
    d29: schedule.d29,
    d30: schedule.d30,
    d31: schedule.d31,
    dLast: schedule.dLast,

    minDurationHours: schedule.minDurationHours,
    minDurationMinutes: schedule.minDurationMinutes,
    maxDurationHours: schedule.maxDurationHours,
    maxDurationMinutes: schedule.maxDurationMinutes,
    timeStart: schedule.timeStart,
    workTimeMode: schedule.workTimeMode,
    timeSlots: schedule.timeSlots?.map(mapTimeSlotToResponseDto) ?? [],

    status: schedule.status,

    rank: schedule.rank,
  };
};
