
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.13.0
 * Query Engine version: 361e86d0ea4987e9f53a565309b3eed797a6bcbd
 */
Prisma.prismaVersion = {
  client: "6.13.0",
  engine: "361e86d0ea4987e9f53a565309b3eed797a6bcbd"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CityScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  region: 'region'
};

exports.Prisma.GameScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  timeStart: 'timeStart',
  timeEnd: 'timeEnd',
  date: 'date',
  status: 'status',
  level: 'level',
  countMembersMin: 'countMembersMin',
  countMembersMax: 'countMembersMax',
  description: 'description',
  requestMode: 'requestMode',
  placeId: 'placeId',
  sportId: 'sportId'
};

exports.Prisma.GameUserScalarFieldEnum = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  gameId: 'gameId',
  userId: 'userId',
  role: 'role',
  status: 'status'
};

exports.Prisma.PlaceScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  description: 'description',
  ownerId: 'ownerId',
  isIndoor: 'isIndoor',
  isFree: 'isFree',
  cityId: 'cityId',
  latitude: 'latitude',
  longitude: 'longitude'
};

exports.Prisma.PlaceFavoriteScalarFieldEnum = {
  createdAt: 'createdAt',
  userId: 'userId',
  placeId: 'placeId'
};

exports.Prisma.PlaceCoversScalarFieldEnum = {
  id: 'id',
  order: 'order',
  placeId: 'placeId',
  createdAt: 'createdAt'
};

exports.Prisma.PlaceSportScalarFieldEnum = {
  createdAt: 'createdAt',
  sportId: 'sportId',
  placeId: 'placeId'
};

exports.Prisma.ScheduleScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  placeId: 'placeId',
  startDate: 'startDate',
  stopDate: 'stopDate',
  name: 'name',
  repeatMode: 'repeatMode',
  repeatStep: 'repeatStep',
  m1: 'm1',
  m2: 'm2',
  m3: 'm3',
  m4: 'm4',
  m5: 'm5',
  m6: 'm6',
  m7: 'm7',
  m8: 'm8',
  m9: 'm9',
  m10: 'm10',
  m11: 'm11',
  m12: 'm12',
  w1: 'w1',
  w2: 'w2',
  w3: 'w3',
  w4: 'w4',
  wLast: 'wLast',
  wd1: 'wd1',
  wd2: 'wd2',
  wd3: 'wd3',
  wd4: 'wd4',
  wd5: 'wd5',
  wd6: 'wd6',
  wd7: 'wd7',
  d1: 'd1',
  d2: 'd2',
  d3: 'd3',
  d4: 'd4',
  d5: 'd5',
  d6: 'd6',
  d7: 'd7',
  d8: 'd8',
  d9: 'd9',
  d10: 'd10',
  d11: 'd11',
  d12: 'd12',
  d13: 'd13',
  d14: 'd14',
  d15: 'd15',
  d16: 'd16',
  d17: 'd17',
  d18: 'd18',
  d19: 'd19',
  d20: 'd20',
  d21: 'd21',
  d22: 'd22',
  d23: 'd23',
  d24: 'd24',
  d25: 'd25',
  d26: 'd26',
  d27: 'd27',
  d28: 'd28',
  d29: 'd29',
  d30: 'd30',
  d31: 'd31',
  dLast: 'dLast',
  workTimeMode: 'workTimeMode',
  minDurationHours: 'minDurationHours',
  minDurationMinutes: 'minDurationMinutes',
  maxDurationHours: 'maxDurationHours',
  maxDurationMinutes: 'maxDurationMinutes',
  timeStart: 'timeStart',
  rank: 'rank',
  status: 'status'
};

exports.Prisma.TimeSlotScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  timeStart: 'timeStart',
  timeEnd: 'timeEnd',
  scheduleId: 'scheduleId'
};

exports.Prisma.SportScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  idx: 'idx',
  email: 'email',
  keycloakId: 'keycloakId',
  telegramId: 'telegramId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  username: 'username',
  avatar: 'avatar'
};

exports.Prisma.UserFavoriteScalarFieldEnum = {
  userId: 'userId',
  favoriteId: 'favoriteId',
  createdAt: 'createdAt'
};

exports.Prisma.UserSportScalarFieldEnum = {
  createdAt: 'createdAt',
  sportId: 'sportId',
  userId: 'userId'
};

exports.Prisma.UserTgLinkerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.GameStatus = exports.$Enums.GameStatus = {
  DRAFT: 'DRAFT',
  APROVED: 'APROVED'
};

exports.GameLevel = exports.$Enums.GameLevel = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD'
};

exports.RequestMode = exports.$Enums.RequestMode = {
  PRIVATE: 'PRIVATE',
  MODERATE: 'MODERATE',
  PUBLIC: 'PUBLIC'
};

exports.GameUserRole = exports.$Enums.GameUserRole = {
  MEMBER: 'MEMBER',
  CREATOR: 'CREATOR'
};

exports.GameUserStatus = exports.$Enums.GameUserStatus = {
  INVITED: 'INVITED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  REQUESTED: 'REQUESTED',
  ALLOWED: 'ALLOWED',
  DECLINED: 'DECLINED'
};

exports.CalendarRepeatMode = exports.$Enums.CalendarRepeatMode = {
  ONCE: 'ONCE',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  CALENDDAYS: 'CALENDDAYS',
  WEEKDAYS: 'WEEKDAYS'
};

exports.WorkTimeMode = exports.$Enums.WorkTimeMode = {
  TIMEGRID: 'TIMEGRID',
  CUSTOM: 'CUSTOM',
  DAILY: 'DAILY',
  NONE: 'NONE'
};

exports.ScheduleStatus = exports.$Enums.ScheduleStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED'
};

exports.Prisma.ModelName = {
  City: 'City',
  Game: 'Game',
  GameUser: 'GameUser',
  Place: 'Place',
  PlaceFavorite: 'PlaceFavorite',
  PlaceCovers: 'PlaceCovers',
  PlaceSport: 'PlaceSport',
  Schedule: 'Schedule',
  TimeSlot: 'TimeSlot',
  Sport: 'Sport',
  User: 'User',
  UserFavorite: 'UserFavorite',
  UserSport: 'UserSport',
  UserTgLinker: 'UserTgLinker'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
